update=Mon 02 Apr 2018 08:04:48 PM EDT
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../global libraries
[eeschema/libraries]
LibName1=/home/matt/Development/kicad/global libraries/library/74xgxx
LibName2=/home/matt/Development/kicad/global libraries/library/74xx
LibName3=/home/matt/Development/kicad/global libraries/library/ac-dc
LibName4=/home/matt/Development/kicad/global libraries/library/actel
LibName5=/home/matt/Development/kicad/global libraries/library/adc-dac
LibName6=/home/matt/Development/kicad/global libraries/library/allegro
LibName7=/home/matt/Development/kicad/global libraries/library/Altera
LibName8=/home/matt/Development/kicad/global libraries/library/analog_devices
LibName9=/home/matt/Development/kicad/global libraries/library/analog_switches
LibName10=/home/matt/Development/kicad/global libraries/library/atmel
LibName11=/home/matt/Development/kicad/global libraries/library/audio
LibName12=/home/matt/Development/kicad/global libraries/library/battery_management
LibName13=/home/matt/Development/kicad/global libraries/library/bbd
LibName14=/home/matt/Development/kicad/global libraries/library/bosch
LibName15=/home/matt/Development/kicad/global libraries/library/brooktre
LibName16=/home/matt/Development/kicad/global libraries/library/cmos4000
LibName17=/home/matt/Development/kicad/global libraries/library/cmos_ieee
LibName18=/home/matt/Development/kicad/global libraries/library/conn
LibName19=/home/matt/Development/kicad/global libraries/library/contrib
LibName20=/home/matt/Development/kicad/global libraries/library/cypress
LibName21=/home/matt/Development/kicad/global libraries/library/dc-dc
LibName22=/home/matt/Development/kicad/global libraries/library/device
LibName23=/home/matt/Development/kicad/global libraries/library/digital-audio
LibName24=/home/matt/Development/kicad/global libraries/library/diode
LibName25=/home/matt/Development/kicad/global libraries/library/display
LibName26=/home/matt/Development/kicad/global libraries/library/dsp
LibName27=/home/matt/Development/kicad/global libraries/library/elec-unifil
LibName28=/home/matt/Development/kicad/global libraries/library/ESD_Protection
LibName29=/home/matt/Development/kicad/global libraries/library/ESP8266
LibName30=/home/matt/Development/kicad/global libraries/library/ftdi
LibName31=/home/matt/Development/kicad/global libraries/library/gennum
LibName32=/home/matt/Development/kicad/global libraries/library/graphic
LibName33=/home/matt/Development/kicad/global libraries/library/hc11
LibName34=/home/matt/Development/kicad/global libraries/library/infineon
LibName35=/home/matt/Development/kicad/global libraries/library/intel
LibName36=/home/matt/Development/kicad/global libraries/library/interface
LibName37=/home/matt/Development/kicad/global libraries/library/intersil
LibName38=/home/matt/Development/kicad/global libraries/library/ir
LibName39=/home/matt/Development/kicad/global libraries/library/Lattice
LibName40=/home/matt/Development/kicad/global libraries/library/leds
LibName41=/home/matt/Development/kicad/global libraries/library/LEM
LibName42=/home/matt/Development/kicad/global libraries/library/linear
LibName43=/home/matt/Development/kicad/global libraries/library/logo
LibName44=/home/matt/Development/kicad/global libraries/library/maxim
LibName45=/home/matt/Development/kicad/global libraries/library/mechanical
LibName46=/home/matt/Development/kicad/global libraries/library/memory
LibName47=/home/matt/Development/kicad/global libraries/library/microchip
LibName48=/home/matt/Development/kicad/global libraries/library/microchip_dspic33dsc
LibName49=/home/matt/Development/kicad/global libraries/library/microchip_pic10mcu
LibName50=/home/matt/Development/kicad/global libraries/library/microchip_pic12mcu
LibName51=/home/matt/Development/kicad/global libraries/library/microchip_pic16mcu
LibName52=/home/matt/Development/kicad/global libraries/library/microchip_pic18mcu
LibName53=/home/matt/Development/kicad/global libraries/library/microchip_pic24mcu
LibName54=/home/matt/Development/kicad/global libraries/library/microchip_pic32mcu
LibName55=/home/matt/Development/kicad/global libraries/library/microcontrollers
LibName56=/home/matt/Development/kicad/global libraries/library/modules
LibName57=/home/matt/Development/kicad/global libraries/library/motor_drivers
LibName58=/home/matt/Development/kicad/global libraries/library/motorola
LibName59=/home/matt/Development/kicad/global libraries/library/motors
LibName60=/home/matt/Development/kicad/global libraries/library/msp430
LibName61=/home/matt/Development/kicad/global libraries/library/MSP430F1610-F1611-F1612
LibName62=/home/matt/Development/kicad/global libraries/library/MSP430F5310
LibName63=/home/matt/Development/kicad/global libraries/library/MSP430F5435-F5437-F5418IPN-80PIN
LibName64=/home/matt/Development/kicad/global libraries/library/MSP430F5436-F5438-F5419IPZ-100PIN
LibName65=/home/matt/Development/kicad/global libraries/library/MSP430G2553-DIP-20
LibName66=/home/matt/Development/kicad/global libraries/library/MSP430G2553-TSSOP-28
LibName67=/home/matt/Development/kicad/global libraries/library/nordicsemi
LibName68=/home/matt/Development/kicad/global libraries/library/nxp
LibName69=/home/matt/Development/kicad/global libraries/library/nxp_armmcu
LibName70=/home/matt/Development/kicad/global libraries/library/onsemi
LibName71=/home/matt/Development/kicad/global libraries/library/opto
LibName72=/home/matt/Development/kicad/global libraries/library/Oscillators
LibName73=/home/matt/Development/kicad/global libraries/library/philips
LibName74=/home/matt/Development/kicad/global libraries/library/power
LibName75=/home/matt/Development/kicad/global libraries/library/powerint
LibName76=/home/matt/Development/kicad/global libraries/library/Power_Management
LibName77=/home/matt/Development/kicad/global libraries/library/pspice
LibName78=/home/matt/Development/kicad/global libraries/library/references
LibName79=/home/matt/Development/kicad/global libraries/library/regul
LibName80=/home/matt/Development/kicad/global libraries/library/relays
LibName81=/home/matt/Development/kicad/global libraries/library/rfcom
LibName82=/home/matt/Development/kicad/global libraries/library/RFSolutions
LibName83=/home/matt/Development/kicad/global libraries/library/sensors
LibName84=/home/matt/Development/kicad/global libraries/library/silabs
LibName85=/home/matt/Development/kicad/global libraries/library/siliconi
LibName86=/home/matt/Development/kicad/global libraries/library/stm8
LibName87=/home/matt/Development/kicad/global libraries/library/stm32
LibName88=/home/matt/Development/kicad/global libraries/library/supertex
LibName89=/home/matt/Development/kicad/global libraries/library/switches
LibName90=/home/matt/Development/kicad/global libraries/library/texas
LibName91=/home/matt/Development/kicad/global libraries/library/transf
LibName92=/home/matt/Development/kicad/global libraries/library/transistors
LibName93=/home/matt/Development/kicad/global libraries/library/triac_thyristor
LibName94=/home/matt/Development/kicad/global libraries/library/ttl_ieee
LibName95=/home/matt/Development/kicad/global libraries/library/valves
LibName96=/home/matt/Development/kicad/global libraries/library/video
LibName97=/home/matt/Development/kicad/global libraries/library/wiznet
LibName98=/home/matt/Development/kicad/global libraries/library/Worldsemi
LibName99=/home/matt/Development/kicad/global libraries/library/Xicor
LibName100=/home/matt/Development/kicad/global libraries/library/xilinx
LibName101=/home/matt/Development/kicad/global libraries/library/zdt1053ta
LibName102=/home/matt/Development/kicad/global libraries/library/zetex
LibName103=/home/matt/Development/kicad/global libraries/library/Zilog
